language: ruby
rvm:
  - 2.6.3

script:
  - bundle config set deployment 'true'
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer --allow-hash-href --url-ignore https://otr.im//404.html,https://otr.im//about/,https://otr.im//feed.xml,https://otr.im//download/,https://otr.im//info/,https://otr.im//team/ ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
