language: ruby
rvm:
  - 2.6.3

script:
  - bundle config set deployment 'true'
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer --url-ignore "/#.*/" ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
